default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do
    scan(
      workspace: "Github.xcodeproj/project.xcworkspace",
      scheme: "Github",
      clean: true
    )
  end

  desc "Sync certificates and provisioning profiles"
  lane :sync_certificates do
    if ENV["CI"]
      setup_ci
    end

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_API_KEY_PATH"],
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    match(
      type: "appstore",
      api_key: api_key,
      readonly: is_ci
    )
  end

  desc "Build the app"
  lane :build do
    sync_certificates

    gym(
      workspace: "Github.xcodeproj/project.xcworkspace",
      scheme: "Github",
      clean: true,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "biaogioni.Github" => "match AppStore biaogioni.Github"
        }
      }
    )
  end

  desc "Upload to App Store"
  lane :delivery do
    build

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_API_KEY_PATH"],
      duration: 1200,
      in_house: false
    )

    upload_to_app_store(
      api_key: api_key,
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false
    )
  end
end
